# Generated by Django 5.1.6 on 2025-04-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0035_alter_comment_content'),
        ('socialmediaapp', '0036_family_and_post'),
    ]

    operations = [
    ]
