# Generated by Django 5.1.6 on 2025-04-07 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0037_merge_0035_alter_comment_content_0036_family_and_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmediaapp.family')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmediaapp.familypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
