# Generated by Django 5.1.6 on 2025-04-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0038_familycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyComment',
        ),
    ]
